### ISSUE TITLE
ローディング時間わけわかんないくらい長いのどうにかする＾ｑ＾

### ISSUE THREAD

**Issue by higedamc** [higedamc/kiatsu#4]
FutureBuilder二個使ってるのとかコンテナとか色々包み込みまくってるのが多分原因なのでどうにかしたい＾＾ｑ

**Comment by harunonsystem** [comment]
ここにヒントあるかも・・・？
https://itome.team/blog/2019/12/flutter-advent-calendar-day8/

**Comment by higedamc** [comment]
むちゃくちゃ爆速になったのでクローズします！
